name: StaffMode
version: ${project.version}
main: me.kr_gaming2005.staffmode.staffmodemain.StaffModeMain
api-version: 1.13
authors: [KR_GAMING2005]
description: Puts player in invis mode and gives them som staff tools
softdepend: [SuperVanish, PremiumVanish]
commands:
  Staffmode:
    permission: staffmode.use
    description: Allows player to toggle staffmode.
permissions:
  staffmode.use:
    default: op
  staffmode.*:
    default: op
    children:
      staffmode.use: true